In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nadyinky/sephora-products-and-skincare-reviews")

print("Path to dataset files:", path)

/opt/anaconda3/envs/stat230A/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /Users/donjhaiholland/.cache/kagglehub/datasets/nadyinky/sephora-products-and-skincare-reviews/2.archive...

100%|██████████| 147M/147M [00:05<00:00, 30.3MB/s]

Extracting files...

Path to dataset files: /Users/donjhaiholland/.cache/kagglehub/datasets/nadyinky/sephora-products-and-skincare-reviews/versions/2

In [ ]:
import os

path = "/Users/donjhaiholland/.cache/kagglehub/datasets/nadyinky/sephora-products-and-skincare-reviews/versions/2"
path_list = os.listdir(path)
path_list

['product_info.csv',
 'reviews_0-250.csv',
 'reviews_1250-end.csv',
 'reviews_750-1250.csv',
 'reviews_250-500.csv',
 'reviews_500-750.csv']

In [45]:
import pandas as pd

# products = pd.read_csv(f"{path}/product_info.csv")
# reviews = pd.read_csv(f"{path}/reviews.csv")

# products_ = path_list[0]
# reviews_path = path_list[1:]
# for path in path_list:



products_path = os.path.join(path, 'product_info.csv')
r_path_1 = os.path.join(path, "reviews_0-250.csv")
r_path_2 = os.path.join(path, "reviews_250-500.csv")
r_path_3 = os.path.join(path, "reviews_250-500.csv")
r_path_4 = os.path.join(path, "reviews_750-1250.csv")
r_path_5 = os.path.join(path, "reviews_1250-end.csv")


products = pd.read_csv(products_path)
reviews_1 = pd.read_csv(r_path_1, index_col=0)
reviews_2 = pd.read_csv(r_path_2, index_col=0)
reviews_3 = pd.read_csv(r_path_3, index_col=0)
reviews_4 = pd.read_csv(r_path_4, index_col=0)
reviews_5 = pd.read_csv(r_path_5, index_col=0)

/var/folders/y3/bdttdwmn6k9gt37x0m1j7q540000gn/T/ipykernel_24849/2499718909.py:21: DtypeWarning: Columns (0: rating) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_1 = pd.read_csv(r_path_1, index_col=0)
/var/folders/y3/bdttdwmn6k9gt37x0m1j7q540000gn/T/ipykernel_24849/2499718909.py:24: DtypeWarning: Columns (0: rating) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_4 = pd.read_csv(r_path_4, index_col=0)
/var/folders/y3/bdttdwmn6k9gt37x0m1j7q540000gn/T/ipykernel_24849/2499718909.py:25: DtypeWarning: Columns (0: rating) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_5 = pd.read_csv(r_path_5, index_col=0)

In [64]:
print(products.shape)
products

(8494, 27)

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8489,P467659,Couture Clutch Eyeshadow Palette,1070,Yves Saint Laurent,2790,4.4286,7.0,NaN,NaN,NaN,...,0,0,0,NaN,Makeup,Eye,Eye Palettes,0,NaN,NaN
8490,P500874,L'Homme Eau de Parfum,1070,Yves Saint Laurent,2319,4.6367,556.0,2 oz / 60 mL,Size + Concentration + Formulation,2 oz / 60 mL eau de parfum spray,...,0,0,0,"['Layerable Scent', 'Woody & Earthy Scent']",Fragrance,Men,Cologne,1,129.0,129.0
8491,P504428,Mon Paris Eau de Parfum Gift Set,1070,Yves Saint Laurent,1475,5.0000,2.0,NaN,NaN,NaN,...,1,1,0,NaN,Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
8492,P504448,Y Eau de Parfum Gift Set,1070,Yves Saint Laurent,840,NaN,NaN,NaN,NaN,NaN,...,1,0,0,NaN,Fragrance,Value & Gift Sets,Cologne Gift Sets,0,NaN,NaN
8493,P505461,Candy Glaze Lip Gloss Stick Duo with Hyaluroni...,1070,Yves Saint Laurent,193,NaN,NaN,.11 oz / 3.2 mL,Color,NaN,...,1,0,1,"['Hyaluronic Acid', 'High Shine Finish', 'Plum...",Makeup,Lip,Lip Gloss,0,NaN,NaN

In [66]:
reviews = pd.concat([reviews_1, reviews_2, reviews_3, reviews_4, reviews_5])
reviews.info()

<class 'pandas.DataFrame'>
Index: 1184874 entries, 0 to 49976
Data columns (total 18 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   author_id                 1184874 non-null  object
 1   rating                    1184874 non-null  int64
 2   is_recommended            1002703 non-null  float64
 3   helpfulness               571832 non-null   float64
 4   total_feedback_count      1184874 non-null  int64
 5   total_neg_feedback_count  1184874 non-null  int64
 6   total_pos_feedback_count  1184874 non-null  int64
 7   submission_time           1184874 non-null  str
 8   review_text               1183383 non-null  str
 9   review_title              848473 non-null   str
 10  skin_tone                 1002771 non-null  str
 11  eye_color                 957915 non-null   str
 12  skin_type                 1065457 non-null  str
 13  hair_color                941297 non-null   str
 14  product_id                1184874 non-null  str
 15  product_name              1184874 non-null  str
 16  brand_name                1184874 non-null  str
 17  price_usd                 1184874 non-null  float64
dtypes: float64(3), int64(4), object(1), str(10)
memory usage: 171.8+ MB

In [52]:
products.isnull().sum()

product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                278
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd       8043
sale_price_usd        8224
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
child_count              0
child_max_price       5740
child_min_price       5740
dtype: int64

In [55]:
reviews.duplicated().sum()
duplicates = reviews[reviews.duplicated()]

In [57]:
reviews.duplicated().sum()

np.int64(206880)

In [59]:
reviews[reviews.duplicated()].shape

(206880, 18)

In [63]:
d = reviews[reviews.duplicated(
    subset=["author_id", "product_id", "review_text"])
]
d

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
878,22934451719,5,1.0,0.666667,3,1,2,2022-08-05,MY FAVORITE LIP SLEEPING MASK. It feels so goo...,NaN,medium,brown,oily,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2137,33914299569,5,1.0,0.000000,15,15,0,2021-11-07,The Aquaphor healing ointment saves my dry cra...,NaN,fair,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3855,1786504204,4,1.0,0.500000,2,1,1,2021-01-10,Have been using this (the same pot) for the la...,NaN,fairLight,green,combination,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4167,6782858790,5,1.0,0.000000,1,1,0,2020-11-29,I love this product when I put it on at night....,Smells too good!,fair,hazel,normal,brown,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4580,6083729409,5,1.0,NaN,0,0,0,2020-09-20,Love love love this stuff! It smells so fun an...,NaN,fair,hazel,combination,brown,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22178,1319880786,5,1.0,0.400000,5,3,2,2017-11-18,This is a ten star product! I’ve used a silk p...,NaN,fair,brown,combination,brown,P402943,Silk Pillowcase - King,Slip,110.0
22179,1319880786,5,1.0,0.000000,1,1,0,2017-11-18,This is a ten star product! I’ve used a silk p...,NaN,fair,brown,combination,brown,P402943,Silk Pillowcase - King,Slip,110.0
23584,2850702737,3,0.0,0.333333,9,6,3,2021-01-05,I would give this product 2.75 stars. When you...,Not that great at all,lightMedium,brown,combination,brown,P438635,The Pout Sparkling Rosé Hyaluronic Acid Collag...,BeautyBio,39.0
37448,12544492953,5,1.0,0.750000,12,3,9,2021-04-13,This stuff is magic! I have no idea why but it...,Made my face clearer overnight!,fair,blue,combination,blonde,P456997,Night Serum,Dr. Barbara Sturm,310.0
42978,791670733,1,0.0,0.666667,18,6,12,2020-12-25,"La Mer’s Lotion, which is less expensive, will...",La Mer's Treatment Lotion is a lot better!,fair,hazel,normal,brown,P416725,The Revitalizing Hydrating Serum,La Mer,255.0